---
wud_n8n_path: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  31356663383334663234346364346436656238656435653431323063663037323264643534626266
  6334333334376462643934393837323166396536636434650a393637636664306366623661336338
  63623364613730616135616536333139343333336164626362623336636562306466383138666333
  6139373834343739310a663736383737613361353038633831323864663266376364636231306531
  64316463366365636362613438653832666537363938303465633535316362636633633535356163
  3035623535313032376633383465393932393462333139343738
wud_n8n_bearer: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  34393530336232336361386434653763303431346662613136346135666530306233333432356666
  6464303831363064386437663933383439396633323133320a306133613936333938323839656434
  37383963626566383434366364336435333564666130633062326632646539626439663865343535
  6337373533356636300a366535343331323638303636343433316136383933323164373239333235
  62613965386232393034626336663536393530306338383236656565373835373762636239383833
  3065623738383231336639333838326331303966656662336162
