---
steam:
  user: buggyfreak2
accweb:
  version: 1.26.0
  users:
    admin: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      32393939383237336565653435366138396334323334633934306134336661346432633363363532
      3636363437623564643765343733386434616332653164610a303131613838643535383431383564
      38653233383530386262343338323563303163633833653236623565313932363962376330626564
      3463353230643435340a393263323939336536643464326361326236613236376334633434323836
      66346237353366613439306431623035303461333565363332363533613764663837
    moderator: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      36623232653262393261326365353636663635356163613231653234343632303038666537353063
      3036636665356162346163393034306133653463353738650a323761636132383631613532326431
      37653332656563313534616234366633663734333430643562366432333130643032346636653734
      6638653065376361390a363333303565643964333031646266313563643737353734663139343332
      63656230373864366264633830313635343235376366373732616233333833363761
    ro: ro
