---
pve_api_key: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  35643031623439363762346535636235353138653931343162313063343637316432643634623161
  3466633731313063343831336335336262653066343939380a633739303265346261343035316231
  33643830646163643930383631383239343065316363396261333834656536333036626339376261
  3533613363333432650a633131646535653165333866623739376539666631646131383962306434
  63343235383639353830333762376530393339333361336266393362396464373263346564663738
  6536373565376338353966356133646133303366363264353338
