---
- name: NODE_EXPORTER - Download node_exporter to localhost
  delegate_to: localhost
  become: false
  check_mode: false
  block:
    - name: NODE_EXPORTER - Download node_exporter binary to local folder
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/\
          v{{ node_exporter_version }}/\
          node_exporter-{{ node_exporter_version }}\
          .linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-latest.linux-amd64.tar.gz"
        mode: '0644'

    - name: NODE_EXPORTER - Unpack node_exporter binary
      ansible.builtin.unarchive:
        src: "/tmp/node_exporter-latest.linux-amd64.tar.gz"
        dest: "/tmp"
        creates: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"

- name: NODE_EXPORTER - Copy the node_exporter systemd service file
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: "0644"

- name: NODE_EXPORTER - Copy node_exporter binaries
  ansible.builtin.copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: "/usr/local/bin/node_exporter"
    mode: "0755"
    owner: prometheus
    group: prometheus
  notify: Restart node_exporter

- name: NODE_EXPORTER - Create node_exporter file directory
  ansible.builtin.file:
    path: /var/lib/node_exporter/textfile_collector
    state: directory
    mode: "0755"
    owner: prometheus
    group: prometheus
    recurse: true
  when: node_file_exporter | default(false)

- name: NODE_EXPORTER - Make sure service is started
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    state: started
    enabled: true
  ignore_errors: "{{ ansible_check_mode }}"

- name: NODE_EXPORTER - Flush handlers
  ansible.builtin.meta: flush_handlers
